### ISSUE TITLE
Swipe to go back opens drawer

### ISSUE THREAD

**Issue by chrissm79** [allpwrfulroot/yaba-social#1] opened 2017-07-25 19:31 UTC
First of all, thank you for making this repo! So it seems that when you navigate away from the drawer to a nested screen (i.e., an event screen), when attempting to swipe to go back it instead opens up the drawer. You can click the back button but this seems to be an issue that has plagued RN from the very beginning and I have yet to find a proper solution. 

I've tried placing the event screen in a different stack but the back button doesn't render on the next page (along with other issues like not passing down params). 

If there's any advice you can provide on this issue I'd appreciate it, thanks again!!

**Comment by allpwrfulroot** [comment] 2017-07-25 20:08
This doesn't feel like a true bug, more a matter of preferences and expectations? And definitely more noticeable with Android, since with iOS (no back button) it feels like fairly expected behavior.

That said, you're not the only person who has brought up this as an issue. Looks like there are several open issues and pull requests in the `react-navigation` repo, but none have been closed/merged yet. Keep an eye on [#793](https://github.com/react-community/react-navigation/pull/793)?

In the meantime, if it's a deal breaker for your app, the only successful workaround I've heard of has been replacing the DrawerNavigator entirely with `react-native-side-menu` 😕

**Comment by allpwrfulroot** [comment] 2017-12-14 22:56
drawerLockMode now available, although I'm not going to implement here: https://github.com/react-community/react-navigation/pull/1377

Closing

**Closed by allpwrfulroot** 2017-12-14 22:56 UTC
